services:
    local.microdotnet.monitoring.otelcollector:
        container_name: local.microdotnet.monitoring.otelcollector
        hostname: local.microdotnet.monitoring.otelcollector
        image: otel/opentelemetry-collector-contrib:0.111.0
        restart: always
        volumes:
          - ./otelcollector/otel-config.yml:/etc/otelcol-contrib/config.yaml
        ports:
          - 4317:4317     # OTLP over gRPC receiver
          - 4318:4318     # OTLP over HTTP receiver
          # - 9464          # Prometheus exporter
          # - 8888          # metrics endpoint
          # - 1888:1888 # pprof extension
          - 13133:13133 # health_check extension
          # - 55679:55679 # zpages extension
          # - 8888:8888 # Prometheus metrics exposed by the collector
          # - 8889:8889 # Prometheus exporter metrics
          # - 4317:4317 # OTLP gRPC receiver
          # - 4318:4318 # OTLP http receiver
        depends_on:
          - local.microdotnet.monitoring.jaeger
          - local.microdotnet.monitoring.zipkin
          - local.microdotnet.monitoring.prometheus
          - local.microdotnet.monitoring.loki
        networks:
          - local.microdotnet.monitoring
