apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://local.microdotnet.monitoring.prometheus:8080
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
        tlsSkipVerify: true

  - name: Zipkin
    type: zipkin
    url: http://local.microdotnet.monitoring.zipkin:9411
    access: proxy
    orgId: 1
    version: 1
    apiVersion: 1
    isDefault: false

  - name: Jaeger
    type: jaeger
    url: http://local.microdotnet.monitoring.jaeger:16686
    access: proxy
    orgId: 1
    version: 1
    apiVersion: 1
    isDefault: false
  
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://local.microdotnet.monitoring.loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
        derivedFields:
          - datasourceUid: otlp
            matcherRegex: (?:"traceid"):"(\w+)"
            name: TraceID
            url: $${__value.raw}